### ISSUE TITLE
UX - Design Dashboard page

### ISSUE THREAD

**Issue by camiriveron** [istrategylabs/franklin#110]
Main page.
-Show user name
-Option to logout
-List Franklin registered repos
-Button to add new repo

**Comment by felskia** [comment]
Hey Guys!

Would like to talk about the data on all of these pages with you again but was a little behind on this stuff so wanted to push forward with the design. Let me know if you have any questions.

https://www.dropbox.com/s/6muummsvt8y78mb/franklin-dashboard-profile.jpg?dl=0
https://www.dropbox.com/s/5fjbp0i90tdtkcp/franklin-dashboard.jpg?dl=0

Thanks!

Ali

**Comment by camiriveron** [comment]
Hey Ali, awesome work! One comment here:
- The select/remove functionality seems unnecessary for the moment
