### ISSUE TITLE
UX - Detail page

### ISSUE THREAD

**Issue by camiriveron** [istrategylabs/franklin#111]
Information about a repo after clicking on it

**Comment by felskia** [comment]
See my comp here: https://www.dropbox.com/s/r2f9htrlhs3un1u/franklin-dashboard-project.jpg?dl=0

**Comment by camiriveron** [comment]
Some comments:
- Move plus box to the end of the list
- The deploy button should be inside each environment 
- Remove is deleting the project from franklin?
