### ISSUE TITLE
Ensure repo_name is unique and remove "id" field

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#19]

**Comment by oudeismetis** [comment]
Repo name is not "unique". Abrahams just pointed out that ISL repos can and will get renamed from time-to-time. Also, we'll like rename the "istrategylabs" org to be "ISL" at some point. Sounds like github has unique IDs it assigns to repos. Not 100% sure we get those in the webhook call, but we probably do. Thus, we should switch to that being the id for the sites model and check against it for future updates. We'll still want repo_name and repo_owner, but more for just constructing URLs, etc.

**Comment by JulianGindi** [comment]
Sounds good. Let's see if we get something unique from Github in that hook.
