### ISSUE TITLE
Handle deploying tag releases of static sites

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#67]

**Comment by oudeismetis** [comment]
Implementation will likely be similar to this:

Right now we only accept webhooks that are for `push` events. That might give us what we want, but for a more pure solution, we should only accept webhooks with `create` in the message header. The json payload will contain a `ref_type` with the value `tag`. Thats how we'll know that it's a tag event and not a branch creation. We will then grab the `ref`, which will be the actual tag. We can include configuration for things like "don't deploy if tag contains `rc`, etc." Or "Only deploy tags containing `beta` to this endpoint".

This will allow us to deploy tag events, we of course want all of this configurable by the user so they can deploy all pushes to a specific branch and/or specific types of tags (matching a regex?) and/or other events. We may also want configuration to support multiple environments (different branches or tags for prod, test, etc.) These features are likely out of scope for this story, but shouldn't be forgotten about.
