### ISSUE TITLE
Create automated way to deploy franklin-dashboard

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#95]

**Comment by oudeismetis** [comment]
Can't link it, but franklin-api has a PR to help this effort along.
https://github.com/istrategylabs/franklin-api/pull/45

**Comment by oudeismetis** [comment]
Another PR https://github.com/istrategylabs/franklin-api/pull/48

**Comment by oudeismetis** [comment]
We can't really do this at this time. There is a way to init things in Franklin on application startup, but part of this process includes registering a webhook with github and cloning/deploying the repo in builder. Those steps require oauth creds to github and deploy keys. We could do something like "init dashboard when a superuser is created. Superuser creation will require providing a social token for that user". That would solve at least the first step, but feels kinda hacky. Will ponder this more and see if there is a getting solution in January.
