### ISSUE TITLE
Local mock server for testing purposes

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#99]

**Comment by oudeismetis** [comment]
Based on recent testing discussion, this is likely not needed at this time. All of the franklin sub-components appear to have a way to mock external dependencies.

We do have plans for some tests to only run on our integration environment before we do production deploys. These tests will intentionally hit external dependencies and are intended to help speed up final review testing before production deploys.  After we have a decent number of those tests written, we may want a mock server at that time as a way of running those tests in local environments or running them more often. (e.g. nightly)
